// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-shrimp-rates.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.1";
function env(key) {
  const v = globalThis.process?.env?.[key] ?? Deno?.env?.get?.(key);
  if (!v) throw new Error(`Missing env: ${key}`);
  return v;
}
function supabaseAnon() {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_PUBLISHABLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-shrimp-rates.ts
var get_shrimp_rates_default = defineTool({
  name: "get_shrimp_rates",
  title: "Get daily shrimp rates",
  description: "Fetch the latest per-count shrimp rates across Indian markets (Vannamei / Tiger / Black Tiger). Returns rows sorted by newest first.",
  inputSchema: {
    market: z.string().optional().describe("Optional market filter, e.g. 'Vijayawada', 'Nellore'."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ market, limit }) => {
    const sb = supabaseAnon();
    let q = sb.from("shrimp_rates").select("*").order("created_at", { ascending: false }).limit(limit);
    if (market) q = q.ilike("market", `%${market}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Returned ${data?.length ?? 0} shrimp rate rows.` }],
      structuredContent: { rates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-fish-rates.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_fish_rates_default = defineTool2({
  name: "get_fish_rates",
  title: "Get daily fish rates",
  description: "Fetch the latest daily fish market rates. Uses the shrimp_rates table filtered to fish species when present; otherwise returns the same rate feed.",
  inputSchema: {
    species: z2.string().optional().describe("Optional species filter, e.g. 'Rohu', 'Katla'."),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ species, limit }) => {
    const sb = supabaseAnon();
    let q = sb.from("shrimp_rates").select("*").order("created_at", { ascending: false }).limit(limit);
    if (species) q = q.ilike("species", `%${species}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Returned ${data?.length ?? 0} rate rows.` }],
      structuredContent: { rates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-farms.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_farms_default = defineTool3({
  name: "list_my_farms",
  title: "List my farms",
  description: "List the farms owned by the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("farms").select("*").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `You have ${data?.length ?? 0} farm(s).` }],
      structuredContent: { farms: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's Ganga Store orders, newest first.",
  inputSchema: { limit: z3.number().int().min(1).max(100).default(25) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("orders").select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Returned ${data?.length ?? 0} orders.` }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-health-reports.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_health_reports_default = defineTool5({
  name: "list_my_health_reports",
  title: "List my aqua health reports",
  description: "List the signed-in user's saved aqua health / disease diagnosis reports.",
  inputSchema: { limit: z4.number().int().min(1).max(100).default(25) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("health_reports").select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Returned ${data?.length ?? 0} health reports.` }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/schedule-task.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var schedule_task_default = defineTool6({
  name: "schedule_task",
  title: "Schedule a task",
  description: "Add a task to the signed-in user's in-app calendar (agent_scheduled_tasks). Use for reminders like water testing, feeding, harvest, or follow-ups.",
  inputSchema: {
    title: z5.string().min(1),
    description: z5.string().optional(),
    due_date: z5.string().optional().describe("ISO 8601 datetime, e.g. 2026-07-25T09:00:00Z"),
    email_recipient: z5.string().email().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, due_date, email_recipient }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("agent_scheduled_tasks").insert({
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      due_date: due_date ?? null,
      email_recipient: email_recipient ?? null,
      source: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Scheduled task "${title}".` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/search-doctors.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var search_doctors_default = defineTool7({
  name: "search_doctors",
  title: "Search aquaculture doctors",
  description: "Search the doctor directory by name, specialization, or city.",
  inputSchema: {
    query: z6.string().optional(),
    city: z6.string().optional(),
    limit: z6.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("doctors").select("*").limit(limit);
    if (query) q = q.or(`name.ilike.%${query}%,specialization.ilike.%${query}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} doctors.` }],
      structuredContent: { doctors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-hatcheries.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^3.25.76";
var search_hatcheries_default = defineTool8({
  name: "search_hatcheries",
  title: "Search hatcheries & aqua stores",
  description: "Search the hatchery / aqua-store directory by name or city.",
  inputSchema: {
    query: z7.string().optional(),
    city: z7.string().optional(),
    limit: z7.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("hatcheries").select("*").limit(limit);
    if (query) q = q.ilike("name", `%${query}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} hatcheries.` }],
      structuredContent: { hatcheries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "whdgqppeitkjdezdjalb";
var mcp_default = defineMcp({
  name: "gangaputra-mcp",
  title: "GANGAPUTRA",
  version: "0.1.0",
  instructions: "Tools for the GANGAPUTRA aquaculture platform. Use these to fetch daily shrimp/fish market rates across Indian markets, look up doctors and hatcheries, and \u2014 when authenticated as a farmer \u2014 list the caller's own farms, orders, and health reports, or schedule a task on their calendar.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_shrimp_rates_default,
    get_fish_rates_default,
    search_doctors_default,
    search_hatcheries_default,
    list_my_farms_default,
    list_my_orders_default,
    list_my_health_reports_default,
    schedule_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
